## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'leco'

package-url = 'https://github.com/pymeasure/pymodaq_plugins_leco'
description = 'Set of PyMoDAQ plugins for controlling instruments via the Laboratory Experiment Control Protocol (LECO)'

author = 'Benedikt Burger'
author-email = 'benedikt.burger@physik.tu-darmstadt.de'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0', 'pyleco']
